### ISSUE TITLE
Build Game

### ISSUE THREAD

**Issue by AlexProudfoot** [the-infocom-files/zork0#2]
Build the game using the ZILF toolset. Eliminate compilation and startup errors where necessary.

**Comment by AlexProudfoot** [comment]
Ensure the main file has a release and a version. The names of included files should be in lower case for linux/macos compilations. Also, use compiler include paths to include zillib. Also, use \<INSERT-FILE\> instead of \<XFLOAD\>.

**Comment by AlexProudfoot** [comment]
The compiler reports 2 errors in game specific files.
```
[error MDL0200]
<internally created FORM>: calling unassigned atom: GET-CLASSIFICATION
  in DIRECTIONS called at defs.zil:239
  in INSERT-FILE called at zork0.zil:43

[error MDL0200]
hints.zil:13: calling unassigned atom: CONSTRUCT-HINTS
  in CONSTANT called at hints.zil:12
  in INSERT-FILE called at zork0.zil:71
```
The compiler also reports 3 errors in library files.
See https://github.com/the-infocom-files/zillib/issues/2#issuecomment-588111109.

**Comment by AlexProudfoot** [comment]
Fix the library files first.

**Comment by AlexProudfoot** [comment]
The compiler barfs...
```
Unhandled Exception: System.ArgumentException: Global symbol already defined: PLURAL
Parameter name: name
   at Zilf.Emit.Zap.GameBuilder.DefineConstant(String name, IOperand value)
   at Zilf.Compiler.Compilation.PrepareConstantBuilders(ZilModelObject lastObject)
   at Zilf.Compiler.Compilation.Compile()
   at Zilf.Compiler.FrontEnd.InterpretOrCompile
      (Context ctx, String inputFileName, String outputFileName,
       Boolean wantCompile, Boolean wantDebugInfo)
   at Zilf.Program.<>c__DisplayClass2_0.<Main>b__1(FrontEnd frontEnd)
   at Zilf.Program.<Main>g__WrapInFrontEnd|2_0(Func`2 func)
   at Zilf.Program.Main(String[] args)
```

**Comment by AlexProudfoot** [comment]
This can be avoided by commenting out the following at line 102 of defs.zil.
```zil
<REPLACE-DEFINITION	PLURAL <CONSTANT PLURAL PLURALBIT>>
```

**Comment by AlexProudfoot** [comment]
The compiler now reports 3 errors in game specific files.
```
[error ZIL0122]
globals.zil:1627: unrecognized routine or instruction: ABS

[error ZIL0103]
fenshire.zil:916: bare atom 'X' used as operand is not a global variable

[error ZIL0103]
fenshire.zil:995: bare atom 'X' used as operand is not a global variable
```
The compiler also reports 8 errors in library files.
See https://github.com/the-infocom-files/zillib/issues/2#issuecomment-588150237.

**Comment by AlexProudfoot** [comment]
Fix the library files first.

**Comment by AlexProudfoot** [comment]
The compiler now reports 2 errors in game specific files.
```
[error ZIL0103] 
fenshire.zil:916: bare atom 'X' used as operand is not a global variable

[error ZIL0103]
fenshire.zil:995: bare atom 'X' used as operand is not a global variable
```
The compiler also reports a warning in a library file.
See https://github.com/the-infocom-files/zillib/issues/2#issuecomment-588168259.

**Comment by AlexProudfoot** [comment]
Disable compilation flag P-ARTHUR as in the example provided by [Jesse McGrew](https://github.com/taradinoc).

**Comment by AlexProudfoot** [comment]
Change \<INPUT X\> to \<INPUT 1\> as in the example provided by [Jesse McGrew](https://github.com/taradinoc).

**Comment by AlexProudfoot** [comment]
No build errors.

**Comment by AlexProudfoot** [comment]
Tidy the main file. Remove extraneous statements.

**Comment by AlexProudfoot** [comment]
Removed \<SET REDEFINE T\>.
The compiler now reports 5 errors.
```
[error MDL0214]
..\zillib\parser\BASEDEFS.mud:118: DEFMAC: already defined: VERSION?
  in INCLUDE called at D:\Alex\Documents\Projects\The Infocom Files\zork0\defs.zil:8
  in INSERT-FILE called at zork0.zil:36

[error MDL0214]
misc.zil:25: DEFMAC: already defined: VERB?
  in INSERT-FILE called at zork0.zil:39

[error MDL0214]
misc.zil:387: GLOBAL: already defined: P-NUMBER
  in INSERT-FILE called at zork0.zil:39

[error MDL0214]
globals.zil:17: GLOBAL: already defined: LIT
  in INSERT-FILE called at zork0.zil:44

[error MDL0214]
globals.zil:1611: GLOBAL: already defined: WIDTH
  in INSERT-FILE called at zork0.zil:44
```

**Comment by AlexProudfoot** [comment]
I can't find the second definition of the VERSION? macro.

**Comment by AlexProudfoot** [comment]
I've put back \<SET REDEFINE T\> because this seems like a complicated issue to do with the file/definitions/package inclusion structure of the project. I'll tackle this later as a separate issue.

**Comment by AlexProudfoot** [comment]
Convert includes and uses to lowercase for Linux compilations. Also remove references to standard packages (such as NEWSTRUC) which are not included in the closure.
